FROM openjdk:8-jdk-alpine
MAINTAINER niveussolutions.com
COPY target/spring-boot-crud-operationsoss-0.0.1-SNAPSHOT.jar spring-boot-crud-operationsoss-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/spring-boot-crud-operationsoss-0.0.1-SNAPSHOT.jar"]